create proc MyRestore
@pathfile nvarchar(500)
AS
ALTER DataBase DBAzmoon SET OFFLINE WITH ROLLBACK IMMEDIATE
RESTORE DATABASE DBAzmoon FROM DISK =@pathfile WITH REPLACE 
ALTER DATABASE DBAzmoon SET ONLINE
GO